title: Appboy
description: The best site ever!
url: "http://lisunshiny.github.io/mktngd"
markdown: kramdown

sass:
    style: compressed     # Minifies compiled CSS


facebook: "https://www.facebook.com/appboy"
twitter: "https://twitter.com/appboy"
github: "https://github.com/appboy"
